services:
  frontend:
    container_name: portfolio-frontend
    restart: always
    image: hmohammed2/portfolio:v1.0.0
    build:
      context: "./portfolio-static"
      dockerfile: Dockerfile.prod
    ports:
      - "5001:80"
    volumes:
      - ./portfolio-static:/usr/share/nginx/html:ro
    depends_on:
      - backend

  backend:
    container_name: portfolio-backend
    restart: always
    image: hmohammed2/backend-email:v1.0.0
    build:
      context: "./backend"
      dockerfile: Dockerfile.prod
    ports:
      - "127.0.0.1:5002:7777"
    environment:
      - NODE_ENV=production
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
